gweb: Fix warning due to GCC8's cast-function-type
Newer version of gcc are very pendantic:

gweb/giognutls.c: In function ‘g_io_gnutls_dispatch’:
gweb/giognutls.c:307:17: error: cast between incompatible function types from ‘GSourceFunc’ {aka ‘int (*)$

Reported by Ross Burton